branch-defaults:
  staging:
    environment: staging-kriya
environment-defaults:
  staging-kriya:
    branch: null
    repository: null
global:
  application_name: dantos
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running Ruby 2.3 (Passenger
    Standalone)
  default_region: us-west-2
  profile: eb-cli
  sc: git
