# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b1e6e38faccf14a2c1e50ea3c5802a93a70b4fcf084631972887afeaec59e86ef0205fda68324598eefeff1dce79f3e1504c1c398afd3bcab9a90438ff0418a
  facebook_id: 1575146999476595
  facebook_secret: c8658602d4bc063e05202390ea2bdc59
  twitter_id: dWR50KvVyXrmawLoRVmm0gMTn
  twitter_secret: QlvlK52dMABfp67p8QgtyUTgfm4DQUyOvWu1NPDZu1uXiRIh5W
  linkedin_id: 81uw1qwwuoqvrh
  linkedin_secret: 1dPMmv5N58gq2evv
  filestack_key: Akt6oZj2YRamLQYtKyrhzz
  new_relic_key: 671d59be4cc3f018684a1756bb6f327f53e4ca61
  stripe_key: pk_ktMbiAhYGulwQ9OsWCSIkdfF6jagV
  stripe_secret: TiH9IbkGOZ8xduW7M0vUKSTkjWwaauJT

test:
  secret_key_base: f407d69717791016bed512c7019f3d614b451a9b4d040e40b792152800ba7a89f7013c6ae4dba3eb48169b58b0018d1225b35813538d86e592184368a43d672a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  twitter_id: <%= ENV["TWITTER_ID"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  linkedin_id: <%= ENV["LINKEDIN_ID"] %>
  linkedin_secret: <%= ENV["LINKEDIN_SECRET"] %>
  filestack_key: <%= ENV["FILESTACK_KEY"] %>
  new_relic_key: <%= ENV["NEW_RELIC_KEY"] %>
  airbrake_project_id: <%= ENV['AIRBRAKE_PROJECT_ID'] %>
  airbrake_api_key: <%= ENV['AIRBRAKE_API_KEY'] %>
  stripe_key: <%= ENV['STRIPE_KEY'] %>
  stripe_secret: <%= ENV['STRIPE_SECRET'] %>